version: '3'
services:
  back_end:
    build:
      context: ./back_end
      dockerfile: DockerFile
    command: go run *.go
    ports:
      - 8080:8080
    depends_on:
      - postgres
  postgres:
    image: "postgres"
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=root      
    ports:
      - "5432:5432"
    volumes:
      - ./postgres-data:/var/lib/postgresql/data  

  pgadmin-compose:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: "task@go.com"
      PGADMIN_DEFAULT_PASSWORD: "task"
    ports:
      - "54322:80"
    depends_on:
      - postgres
  front_end:
    build:
      context: ./front_end
      dockerfile: DockerFile
    command: node_modules/.bin/nodemon --exec npm start
    ports:
      - "3000:3000"
    volumes:
      - /front_end/node_modules
    depends_on:
      - postgres