FROM node

WORKDIR /front_end

COPY package*.json ./

RUN npm install -D tailwindcss@latest postcss@latest autoprefixer@latest
RUN npm install -g npm@9.4.1
COPY . .

EXPOSE 3000

ENV PORT 3000
CMD ["npm", "start"]