import { Button, Center, Flex, Stack, Text } from "@chakra-ui/react"
import React, { useState } from "react"

import { useColorsPhone } from "@/hooksPerson/colorsPhone"
import CardStylePhone from "../CardStylePhone"
import ListAll from "../ListAll"
import CardAllAddList from "../CardAllAddList"
import TabsLoginOk from "../TabsLoginOk"
import CardStyleWeb from "@/components/ComponentsWeb/CardStyleWeb"
import Head from "next/head"


interface Props {
    cookie: string | undefined;
}
const GetTokenValid = (props: Props) => {
    const allColors = useColorsPhone()
    const [active, setActive] = useState(false);
    return (
        <>
            <Head>
                <title>List Task</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />

            </Head>

            {
                props.cookie != undefined ?
                    < Flex backgroundColor={allColors.bg} width="100vw" justifyContent="center" alignItems="center" flexDirection="column" height="100vh" >
                        <Stack margin="0.5vw">
                            <Button onClick={e => { setActive(state => !state) }}>{active == false ? "Web" : "Mobile"}</Button>
                        </Stack>
                        {active == false ? <CardStylePhone content={<TabsLoginOk contentCreateList={<CardAllAddList />} contentListAll={<ListAll />} />} /> : <CardStyleWeb content={<TabsLoginOk contentCreateList={<CardAllAddList />} contentListAll={<ListAll />} />} />}
                    </Flex > : <Center>
                        <Text>Not Access</Text>
                    </Center>
            }


        </>
    )

}

export default GetTokenValid