import React, { Children, ReactNode, useContext, useEffect, useState } from "react";
import { useGetCookie } from "@/hooksPerson/getCookie";
import { Box, Button, Center, Flex, Stack } from "@chakra-ui/react";
import { useColorsPhone } from "@/hooksPerson/colorsPhone";
import CardStylePhone from "@/components/ComponentsPhone/CardStylePhone";
import CreateUser from "@/components/ComponentsPhone/CreateUser";
import CardStyleWeb from "@/components/ComponentsWeb/CardStyleWeb";
import Head from "next/head";



type Props = {

    children: ReactNode,



};
export const MyContext = React.createContext(false);


export const MyProvider = ({
    children
}: Props) => {
    const [active, setActive] = useState(false);
    const allColors = useColorsPhone()
    return (
        <MyContext.Provider value={active}>
            <Box width="100vw" height="100vh">
                <Head>
                    <title>List Task</title>
                    <meta name="description" content="Generated by create next app" />
                    <meta name="viewport" content="width=device-width, initial-scale=1" />
                    <link rel="icon" href="/favicon.ico" />
                </Head>
                <Center margin="0.3vw">
                    <Button width="10vw" onClick={e => { setActive(state => !state) }}>{active == false ? "Web" : "Mobile"}</Button>
                </Center>
                <Flex backgroundColor={allColors.bg} width="100vw" justifyContent="center" alignItems="center" flexDirection="column" height="100vh">
                    {children}
                </Flex>

            </Box>
        </MyContext.Provider>
    );
};

function teste() {

}