import Head from 'next/head'
import { Flex, Stack, Button, Box } from '@chakra-ui/react';
import { useColorsWeb } from '@/hooksPerson/colorsWeb';
import CardStylePhone from '@/components/ComponentsPhone/CardStylePhone';
import CreateUser from '@/components/ComponentsPhone/CreateUser';
import CardStyleWeb from '@/components/ComponentsWeb/CardStyleWeb';
import { useContext, useState } from 'react';
import { MyContext } from '@/context/cookieContext';


export default function Home() {
  const allColors = useColorsWeb()
  const value = useContext(MyContext)

  return (
    <Box width="100vw" height="100vh">
      <Head>
        <title>List Task</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {value}
    </Box>
  )
}
