import Head from 'next/head'
import CardStylePhone from '@/components/CardStylePhone';
import TitleList from '@/components/Title';
import CardAllAddList from '@/components/CardAllAddList';
import ListAll from '@/components/ListAll';
import { Heading } from '@chakra-ui/react';


export default function Home() {

  return (
    <>
      <Head>
        <title>List Task</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="w-screen h-screen flex   flex-col justify-center items-center">
        <div className='flex flex-row w-11/12 h-full bg-violet-200 items-center justify-around'>
   
          <CardStylePhone styleCss={"bg-violet-300 w-full h-full rounded-2xl"} contentCreateList={<CardAllAddList />} contentListAll={<ListAll />} />
        </div>

      </main>
    </>
  )
}
