import Head from 'next/head'
import {Flex} from '@chakra-ui/react';
import CardStylePhone from '@/components/ComponentsPhone/CardStylePhone';
import CardAllAddList from '@/components/ComponentsPhone/CardAllAddList';
import ListAll from '@/components/ComponentsPhone/ListAll';
import TabsLoginOk from '@/components/ComponentsPhone/TabsLoginOk';
import { useColorsPhone } from '@/hooksPerson/colorsPhone';



export default function Home() {
  const allColors= useColorsPhone()
  return (
    <>
      <Head>
        <title>List Task</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Flex backgroundColor={allColors.bg} width="100vw" justifyContent="center" alignItems="center" flexDirection="column" height="100vh">
        <CardStylePhone content={<TabsLoginOk contentCreateList={<CardAllAddList/>} contentListAll={<ListAll/>}/>}/>
      </Flex>
    </>
  )
}
