import Head from 'next/head'
import { Button, Flex, Stack } from '@chakra-ui/react';
import CardStylePhone from '@/components/ComponentsPhone/CardStylePhone';
import CardAllAddList from '@/components/ComponentsPhone/CardAllAddList';
import ListAll from '@/components/ComponentsPhone/ListAll';
import TabsLoginOk from '@/components/ComponentsPhone/TabsLoginOk';
import { useColorsPhone } from '@/hooksPerson/colorsPhone';
import { useState } from 'react';
import CardStyleWeb from '@/components/ComponentsWeb/CardStyleWeb';



export default function Home() {
  const allColors = useColorsPhone()
  const [active, setActive] = useState(false);

  return (
    <>
      <Head>
        <title>List Task</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Flex backgroundColor={allColors.bg} width="100vw" justifyContent="center" alignItems="center" flexDirection="column" height="100vh">
        <Stack margin="0.5vw">
          <Button onClick={e => { setActive(state => !state) }}>{active == false ? "Web" : "Mobile"}</Button>
        </Stack>
        {active == false ? <CardStylePhone content={<TabsLoginOk contentCreateList={<CardAllAddList />} contentListAll={<ListAll />} />} /> : <CardStyleWeb content={<TabsLoginOk contentCreateList={<CardAllAddList />} contentListAll={<ListAll />} />} />}
      </Flex>
    </>
  )
}
