import Head from 'next/head'
import { Button, Flex } from '@chakra-ui/react';
import CardStylePhone from '@/components/ComponentsPhone/CardStylePhone';
import LoginAccess from '@/components/ComponentsPhone/LoginAcess';
import { useColorsPhone } from '@/hooksPerson/colorsPhone';
import React, {useEffect } from 'react'
import { postLogout } from '@/services/handler/login_handler';
import { useMutation } from 'react-query';
import { useMutationPostLogout } from '@/services/handler/muation';



export default function Home() {
  const allColors = useColorsPhone()
  const mutation = useMutation({ mutationFn: postLogout,})
  const logout = useMutationPostLogout()
 
  // useEffect(() => {
  //   mutation.mutate()

  // }, []);
    
 
  return (

    <>
    
      <Head>
        <title>List Task</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Flex backgroundColor={allColors.bg} width="100vw" justifyContent="center" alignItems="center" flexDirection="column" height="100vh">
        <CardStylePhone content={<LoginAccess />} />
      </Flex>
    </>
  )
}