import Head from 'next/head'
import { Box, Button, Flex, Stack } from '@chakra-ui/react';
import CardStylePhone from '@/components/ComponentsPhone/CardStylePhone';
import LoginAccess from '@/components/ComponentsPhone/LoginAcess';
import { useColorsPhone } from '@/hooksPerson/colorsPhone';
import React, { useEffect, useState } from 'react'
import { postLogout } from '@/services/handler/login_handler';
import { useMutation } from 'react-query';
import { useMutationPostLogout } from '@/services/handler/muation';
import CardStyleWeb from '@/components/ComponentsWeb/CardStyleWeb';



export default function Home() {
  const allColors = useColorsPhone()
  const mutation = useMutation({ mutationFn: postLogout, })
  const logout = useMutationPostLogout()
  const [active, setActive] = useState(false);

  return (

    <Box width="100vw" height="100vh">

      <Head>
        <title>List Task</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Flex backgroundColor={allColors.bg} width="100vw" justifyContent="center" alignItems="center" flexDirection="column" height="100vh">
        <Stack margin="0.5vw">
          <Button onClick={e => { setActive(state => !state) }}>{active == false ? "Web" : "Mobile"}</Button>
        </Stack>
        {active == false ? <CardStylePhone content={<LoginAccess />} /> : <CardStyleWeb content={<LoginAccess />} />}
    
      </Flex>
    </Box>
  )
}