FROM golang

# Set the Current Working Directory inside the container
WORKDIR /back_end

# Copy everything from the current directory to the PWD (Present Working Directory) inside the container
COPY go.mod ./
COPY go.sum ./

RUN go mod download

# This container exposes port 8080 to the outside world
EXPOSE 8080

# Run the executable
CMD ["go-sample-app"]