import Head from 'next/head'
import { Inter } from '@next/font/google'
import styles from '@/styles/Home.module.css'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Lists Tasks</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <div className={styles.description}>
          <div className={styles.addlist}>
            <div className={styles.titleDescription}>
              <h3>Add List</h3>
            </div>
            <span>Name: <input type="text" /></span>
            <div className={styles.titleDescription}>
              <h3>Add Tasks</h3>
            </div>

          <span>Title: <input type="text" /></span>
          <span>Description: <input type="text" /></span>
          <span>Concluded: <input type="checkbox" /></span>
          <span>Priority: <input type="checkbox" /></span>
          <span>Time: <input type="time" min="00:00" max="23:00" /></span>
          <button>Save</button>
        </div>
        <div className={styles.list}>

        </div>
      </div>
    </main>
    </>
  )
}
