import Head from 'next/head'
import { Inter } from '@next/font/google'
import styles from '@/styles/Home.module.css'
import Title from '@/components/Title'
import InputTask from '@/components/Input'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Lists Tasks</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <div className={styles.description}>
          <div className={styles.addlist}>
            <Title text='Add List' />
            <InputTask text='Name: ' typeInput="text"/>
            <Title text='Add Task' />
            <InputTask text='Title: ' typeInput="text"/>
            <InputTask text='Description: ' typeInput="text"/>
            <InputTask text='Concluded: ' typeInput="checkbox"/>
            <InputTask text='Priority:' typeInput="checkbox"/>
            <InputTask text='Time:' typeInput="time"/>

            <button >Save</button>
          </div>
          <div className={styles.list}>

          </div>
        </div>
      </main>
    </>
  )
}
